### ISSUE TITLE
学习资料

### ISSUE THREAD

**Issue by Smile-L-up** [CongSun-dlut/BioBERT-MRC#1]
大佬你好，，啥时候可以提供资料学习学习呀

**Comment by CongSun-dlut** [comment]
不敢当，非大佬。感谢您关注我们的工作。该工作我们有开源计划，预计9月底发布整理后的代码。

**Comment by Smile-L-up** [comment]
您谦虚，我其实是想请教您问句构造与选择策。如：一个句子拼接几个问句，问句添加是随机添加么还是？在预测的时候会添加问句么？问句一般包含多少个实体？

**Comment by CongSun-dlut** [comment]
您好！一个句子（Context）拼接一个问句（Query）。Query是自己设计的，不唯一。在预测阶段也构造Query，方式与训练阶段一致。我们设计了几种Query，其中当一个问句包含3个实体（Query-3）时，模型性能要略好一些。具体细节请见论文Biomedical named entity recognition using BERT in the machine reading comprehension framework (https://www.sciencedirect.com/science/article/abs/pii/S1532046421001283)

**Comment by Smile-L-up** [comment]
感谢您的回复，但我还是有一个疑问，拼接的问句也是随机选择一个类型吗？我发现文章中指出，如果有三类实体，就有三类问句，但一个句子只拼接一个问句，这怎么选择呢？

**Comment by CongSun-dlut** [comment]
我们一共使用了六个数据集进行实验，这些数据集可以分为三类，分别是面向化学物、药物和疾病的。但是，就每一个具体数据集而言，其仅对某一个特定类别实体进行标注。所以，对于某一个具体数据集，可以组织成一个句子拼接一个（该数据集面向实体类型的）问句的形式。

**Comment by Smile-L-up** [comment]
您好，我还想请教一下，因为添加了问句的形式，我在每一个周期都会对验证集和测试集进行一次预测。并保存最有模型，但是在最后一次验证最优模型在测试集上的效果时，发现得到的结果与训练时的结果是会不一致的。（意思就是保存的模型对测试集进行预测时也会有出入），不知道您有没有出现这样的问题。还有一个问题想请教的就是，论文写到每次实验跑五次，是设定了唯一的随机种子跑五次还是怎么样的一种形式？希望得到您的解惑。先谢谢您了。

**Comment by CongSun-dlut** [comment]
我们随机选择5个不同随机种子实验5次，共计得到5个实验结果。报告了平均F1值和最大F1值，以及T-TEST显著性检测结果。由于神经网络的随机性，每次实验的运行结果可能会有不同。

**Comment by Smile-L-up** [comment]
您好，我又来请教您了。问句所添加的实体是从哪些数据集中收取的，比如说训练集、验证集、测试集。我感觉不能收集测试集上的实体。所以又来请教您了。

**Comment by CongSun-dlut** [comment]
您好，论文3.2. Construct queries小节中有过描述，“we used biomedical entities from the training/development set of the target dataset to construct queries”，没有用到测试集。详情请见论文Biomedical named entity recognition using BERT in the machine reading comprehension framework (https://www.sciencedirect.com/science/article/abs/pii/S1532046421001283)。
