### ISSUE TITLE
查询生成

### ISSUE THREAD

**Issue by zhangliin** [CongSun-dlut/BioBERT-MRC#2]
您好！我对模型中生成查询的代码很感兴趣。请问可以公开生成查询query的代码吗？

**Comment by zhangliin** [comment]
构造查询

**Comment by CongSun-dlut** [comment]
> 您好！我对模型中生成查询的代码很感兴趣。请问可以公开生成查询query的代码吗？

您好！感谢关注。query部分已在论文中做了详细描述，您可以参考一下文中实现过程。
